using System;
using System.Collections.Generic;
using System.Text;

namespace ArkSaveEditor.Entities.LowLevel.AutoGeneratedClasses
{
    /// <summary>
    /// Defines data for built in maps.
    /// </summary>
    public static class ArkMapDataTable
    {
        public static Dictionary<string, ArkMapData> arkmaps = new Dictionary<string, ArkMapData>
        {
            ////////
            { "Extinction", new ArkMapData
                {
                    displayName = "Extinction",
                    isOfficial = true,
                    isStoryArk = true,
                    backgroundColor = null,
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    captureSize = 860000,
                    mapImageOffset = new Vector2(0, 0),
                    maps = new ArkMapDisplayData[]
                    {
                        new ArkMapDisplayData
                        {
                            name = "Surface",
                            url = "https://tile-assets.deltamap.net/extinction/v1/0/{z}_{x}_{y}.png",
                            description = "Standard map",
                            maximumZoom = 6
                        }
                    }
                }
            },
            ///////
            { "TheCenter", new ArkMapData
                {
                    displayName = "The Center",
                    isOfficial = true,
                    isStoryArk = false,
                    backgroundColor = "#0070C1",
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    captureSize = 1, //Currently not valid
                    mapImageOffset = new Vector2(0, -20511*10),
                    maps = new ArkMapDisplayData[]
                    {
                        new ArkMapDisplayData
                        {
                            name = "Surface",
                            url = "https://tile-assets.deltamap.net/the-center/v1/0/{z}_{x}_{y}.png",
                            description = "Standard map",
                            maximumZoom = 6
                        }
                    }
                }
            },
            ///////
            { "TheIsland", new ArkMapData
                {
                    displayName = "The Island",
                    isOfficial = true,
                    isStoryArk = true,
                    backgroundColor = "#5a55b5",
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    captureSize = 800000,
                    mapImageOffset = new Vector2(0, 0),
                    maps = new ArkMapDisplayData[]
                    {
                        new ArkMapDisplayData
                        {
                            name = "Surface",
                            url = "https://tile-assets.deltamap.net/the-island/v1/0/{z}_{x}_{y}.png",
                            description = "Standard map",
                            maximumZoom = 6
                        }
                    }
                }
            },
            ///////
            { "ScorchedEarth_P", new ArkMapData
                {
                    displayName = "Scorched Earth",
                    isOfficial = true,
                    isStoryArk = true,
                    backgroundColor = null,
                    latLonMultiplier = 8000,
                    bounds = new WorldBounds2D
                    {
                        minX = -320000,
                        minY = -320000,
                        maxX = 320000,
                        maxY = 320000
                    },
                    captureSize = 700000,
                    mapImageOffset = new Vector2(0, 0),
                    maps = new ArkMapDisplayData[]
                    {
                        new ArkMapDisplayData
                        {
                            name = "Surface",
                            url = "https://tile-assets.deltamap.net/scorched-earth/v1/0/{z}_{x}_{y}.png",
                            description = "Standard map",
                            maximumZoom = 6
                        }
                    }
                }
            },
        };
    }
}
